version: 0.0
os: linux
files:
 - source: /webapp/src/main/webapp/index.jsp
   destination: /opt/apache-tomcat-8.5.39/webapps/webapp/
hooks:

BeforeInstall:
    - location: Hello-World/deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: Hello-World/deploy/restart_server
      timeout: 300
      runas: root

