version: 0.0
os: linux
files:
 - source: /var/lib/jenkins/workspace/Java-Web-App/webapp/target/webapp.war
   destination: /opt/apache-tomcat-8.5.39/webapps
hooks:
 BeforeInstall:
   - location: script/install_dependencies.sh
     timeout: 300
     runas: root
 AfterInstall:
   - location: script/install_dependencies01.sh
     timeout: 300
     runas: root
 ApplicationStart:
   - location: script/start_server.sh
     timeout: 300
runas: root
