version: 0.0
os: linux
files:
 - source: /var/lib/jenkins/workspace/Java-Web-App/webapp/target/webapp.war
   destination: /opt/apache-tomcat-8.5.39/webapps
hooks:

BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: root

