version: 0.0
os: linux
files:
  - source: /
    destination: /opt/apache-tomcat-8.5.39/webapps/

hooks:
 
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  
